name: Unit Tests

on:
  push

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: run tests
        run: ./gradlew test